  include:
    entities:
        - input_boolean.allarmediurno
        - input_boolean.allarmenotturno
        - input_boolean.allarmegarage
        - input_boolean.scattaallarme
        - input_boolean.sky
        - input_boolean.appletv
        - input_boolean.dtt
        - input_boolean.pc
        - input_boolean.tvsala
        - input_boolean.telecamere
        - input_boolean.acasa
        - input_boolean.climasala
        - input_boolean.climacamera
        - input_boolean.timerclima
        - cover.apri_basculante
        - switch.switch_3 # Cucina
        - light.faretto
        - light.flos
        - switch.fibaro_system_fgs223_double_relay_switch_3 # Parete Sala
        - switch.fibaro_system_fgs223_double_relay_switch_4 # Scale
        - switch.switch_2 # Corridoio
        - switch.fibaro_system_fgs223_double_relay_switch_6 # Atrio
        - light.hue_color_lamp_1_2 #Lampada Studio 1
        - light.hue_color_lamp_1 #Lampada Studio 2
        - switch.switch # Bagno
        - switch.fibaro_system_fgs223_double_relay_switch # Specchio Bagno
        - switch.plug_158d000154ae22 # Led Bagno
        - switch.fibaro_system_fgs223_double_relay_switch_2 #Camera
        - light.led
        - light.led_2
        - light.led_3
        - switch.plug_158d00015ef7bc # Lampada Sale
        - light.terrazzo_1
        - light.terrazzo_2
        - light.terrazzo_3
        - light.gateway_light_f0b429cc390b
        - switch.sonoff_luci_garage
        - sensor.temperature_158d00011001fc
        - sensor.temperature_158d00015ab8a8
        - sensor.temperature_158d00020ffbbc
        - sensor.temperature_158d00015a6698
        - sensor.temperature_158d0001531ac9
        - sensor.humidity_158d00011001fc
        - sensor.humidity_158d00015ab8a8
        - sensor.humidity_158d00020ffbbc
        - sensor.humidity_158d00015a6698
        - sensor.humidity_158d0001531ac9
        - binary_sensor.water_leak_sensor_158d00023a47c4
        - sensor.qualità_aria
        - binary_sensor.motion_sensor_158d00013f8c44
        - binary_sensor.motion_sensor_158d000132e942
        - binary_sensor.motion_sensor_158d0001232507
        - binary_sensor.motion_sensor_158d00014dca3a
        - binary_sensor.motion_sensor_158d000120ac8c
        - binary_sensor.motion_sensor_158d0001136f8c
        - binary_sensor.motion_sensor_158d0001dac0bd
        - binary_sensor.motion_sensor_158d00010c24fe
        - binary_sensor.motion_sensor_158d000128d5d5
        - binary_sensor.motion_sensor_158d00012cbb86
        - binary_sensor.motion_sensor_158d00011c3211
        - binary_sensor.motion_sensor_158d0001e63075
        - binary_sensor.door_window_sensor_158d000153ab76
        - binary_sensor.door_window_sensor_158d00013e3968
        - binary_sensor.door_window_sensor_158d0001a348e1
        - sensor.widom_ume304_energy_driven_switch_power
        - sensor.unknown_5
        - sensor.fibaro_system_fgs223_double_relay_power_5
        - sensor.fibaro_system_fgs223_double_relay_power_6
        - sensor.fibaro_system_fgs223_double_relay_power_8
        - sensor.fibaro_system_fgs223_double_relay_power_3
        - sensor.fibaro_system_fgs223_double_relay_power
        - sensor.fibaro_system_fgs223_double_relay_power_2
        - sensor.fibaro_system_fgs223_double_relay_power_4
        - sensor.neo_coolcam_power_plug_12a_power_4
        - sensor.neo_coolcam_power_plug_12a_power
        - sensor.neo_coolcam_power_plug_12a_power_2
        - sensor.neo_coolcam_power_plug_12a_power_3
        - sensor.neo_coolcam_power_plug_12a_power_5
        - sensor.consumo_htcamera
        - sensor.consumo_tvsala
        - sensor.badge_costo_consumo
        - sensor.badge_costo_mensile
        - sensor.saldo_crypto
        - input_number.crypto_fine
        - variable.ultimo_movimento
        - input_number.consumo_inizio
        - input_number.consumo_fine
        - input_number.consumo_day
        - input_number.consumo_mese_inizio
        - input_number.consumo_mese_fine
        - input_number.consumo_mese
        - sensor.consumo_oggi
        - sensor.costo_consumo_oggi
        - sensor.consumo_ieri
        - sensor.costo_consumo_ieri
        - sensor.consumo_ieri_mean
        - sensor.costo_ieri_mean
        - sensor.consumo_mensile_oggi
        - sensor.costo_consumo_mese_attuale
        - sensor.costo_consumo_mensile
        - sensor.consumo_attuale
        - sensor.consumo_luci
        - sensor.consumo_elettrodomestici
        - sensor.consumo_studio
        - sensor.consumo_giornaliero_medio
        - sensor.consumo_giornaliero_max
        - sensor.consumo_giornaliero_min
        - sensor.speedtest_download
        - sensor.speedtest_upload
        - sensor.speedtest_ping
        - vacuum.xiaomi_vacuum_cleaner
        - sensor.casa_ufficio
        - sensor.ufficio_casa
        - binary_sensor.water_leak_sensor_158d00023a47c4
        - sensor.stato_lavatrice
        - sensor.stato_lavastoviglie
        - sensor.stato_forno
        - device_tracker.hassio_owntracks
        - device_tracker.hassio_iphoneown
        - device_tracker.beacon_cancello