  auto_start: False
  filter:
      include_entities:
        - input_boolean.automazioni
        - input_boolean.autocucina
        - input_boolean.autoscale
        - input_boolean.autocorridoio
        - input_boolean.autobagno
        - input_boolean.autocamera
        - input_boolean.autostudio
        - input_boolean.autoterrazzo
        - input_boolean.allarmediurno
        - input_boolean.allarmenotturno
        - input_boolean.allarmegarage
        - input_boolean.sky
        - input_boolean.appletv
        - input_boolean.dtt
        - input_boolean.pc
        - input_boolean.tvsala
        - input_boolean.telecamere
        - input_boolean.acasa
        - input_boolean.cromoterrazzo
        - input_boolean.cromocamera
        - input_boolean.cromosala
        - input_boolean.cromostudio
        - input_boolean.cromobagno
        - input_boolean.franchinogoogle
        - input_boolean.pausaskyappletv
        - input_boolean.ambilight
        - input_boolean.tvcamera
        - input_boolean.climasala
        - input_boolean.climacamera
        - input_boolean.superclimasala
        - input_boolean.superclimacamera
        - input_boolean.timerclima
        - input_boolean.inufficio
        - input_boolean.buonanotte
        - input_boolean.timertvcamera
        - input_boolean.timerclima
        - input_boolean.mutoampli
        - media_player.spotify
        - media_player.apple_tv_sala
        - media_player.ampli_denon
        - media_player.bagno
        - switch.fluxer
        - cover.apri_basculante
        - switch.switch_3 # Cucina
        - light.faretto
        - light.flos
        - switch.fibaro_system_fgs223_double_relay_switch_3 # Parete Sala
        - switch.fibaro_system_fgs223_double_relay_switch_4 # Scale
        - switch.switch_2 # Corridoio
        - switch.fibaro_system_fgs223_double_relay_switch_6 # Atrio
        - light.hue_color_lamp_1_2 #Lampada Studio 1
        - light.hue_color_lamp_1 #Lampada Studio 2
        - switch.switch # Bagno
        - switch.fibaro_system_fgs223_double_relay_switch # Specchio Bagno
        - switch.plug_158d000154ae22 # Led Bagno
        - switch.fibaro_system_fgs223_double_relay_switch_2 #Camera
        - light.led
        - light.led_2
        - light.led_3
        - switch.plug_158d00015ef7bc # Lampada Sale
        - switch.plug_158d0001db024c # Led TV Camera
        - light.terrazzo_1
        - light.terrazzo_2
        - light.terrazzo_3
        - light.gateway_light_f0b429cc390b
        - switch.sonoff_luci_garage
        - media_player.ampli_denon
        - fan.xiaomi_miio_device
        - sensor.illumination_f0b429cc390b
        - sensor.illumination_34ce0088b729
        - sensor.illumination_158d0001e63075
        - sensor.temperature_158d00011001fc
        - sensor.temperature_158d00015ab8a8
        - sensor.temperature_158d00020ffbbc
        - sensor.temperature_158d00015a6698
        - sensor.temperature_158d0001531ac9
        - sensor.temperature_158d00020ec48d
        - sensor.humidity_158d00011001fc
        - sensor.humidity_158d00015ab8a8
        - sensor.humidity_158d00020ffbbc
        - sensor.humidity_158d00015a6698
        - sensor.humidity_158d0001531ac9
        - sensor.humidity_158d00020ec48d
        - binary_sensor.water_leak_sensor_158d00023a47c4
        - sensor.qualità_aria
        - binary_sensor.motion_sensor_158d00013f8c44
        - binary_sensor.motion_sensor_158d000132e942
        - binary_sensor.motion_sensor_158d0001232507
        - binary_sensor.motion_sensor_158d00014dca3a
        - binary_sensor.motion_sensor_158d000120ac8c
        - binary_sensor.motion_sensor_158d0001136f8c
        - binary_sensor.motion_sensor_158d0001dac0bd
        - binary_sensor.motion_sensor_158d00010c24fe
        - binary_sensor.motion_sensor_158d000128d5d5
        - binary_sensor.motion_sensor_158d00012cbb86
        - binary_sensor.motion_sensor_158d00011c3211
        - binary_sensor.motion_sensor_158d0001e63075
        - binary_sensor.door_window_sensor_158d000153ab76
        - binary_sensor.door_window_sensor_158d00013e3968
        - binary_sensor.door_window_sensor_158d0001a348e1
        - switch.switch_9 # Forno
        - switch.switch_6 # Frigo
        - switch.switch_7 # Lavasotviglie
        - switch.switch_8 # Lavatrice
        - switch.switch_10 # HT Sala
        - switch.plug_158d000154ae55 # HT Camera
        - switch.plug_158d00015db991 # Power TV Sala