  pcsala:
    name: PC Sala

  sky:
    name: Sky

  appletv:
    name: AppleTV

  pc:
    name: PC

  dtt:
    name: DTT

  tvsala:
    name: TV Sala

  telecamere:
    name: Telecamere

  acasa:
    name: A Casa

  cromoterrazzo:
    name: Cromoterapia Terrazzo

  automazioni:
    name: Automazioni
    initial: on

  autocucina:
    name: Auto Cucina
    initial: on
    
  autoscale:
    name: Auto Scale
    initial: on
    
  autocorridoio:
    name: Auto Corridoio
    initial: on
    
  autobagno:
    name: Auto Bagno
    initial: on
    
  autocamera:
    name: Auto Camera
    initial: on

  autostudio:
    name: Auto Studio
    initial: on

  autoterrazzo:
    name: Auto Terrazzo
    initial: on
    
  allarmediurno:
    name: Allarme Diurno

  allarmenotturno:
    name: Allarme Notturno

  allarmegarage:
    name: Allarme Garage

  scattaallarme:
    name: Scatta Allarme

  cromosala:
    name: Cromoterapia Sala

  cromocamera:
    name: Cromoterapia Camera

  cromostudio:
    name: Cromoterapia Studio

  primoarrivo:
    name: Primo Arrivo

  franchinogoogle:
    name: Franchino
    icon: mdi:broom

  purificatorecameragoogle:
    name: Purificatore Camera Google

  pausaskyappletv:
    name: Pausa
    icon: mdi:pause

  ambilight:
    name: Ambilight
    icon: mdi:spotlight

  tvcamera:
    name: TV Camera
    icon: mdi:remote

  cromobagno:
    name: Cromoterapia Bagno

  climasala:
    name: Clima Sala
    icon: mdi:air-conditioner

  superclimasala:
    name: Super Clima Sala
    icon: mdi:weather-windy

  climacamera:
    name: Clima Camera
    icon: mdi:air-conditioner

  superclimacamera:
    name: Super Clima Camera
    icon: mdi:weather-windy

  inufficio:
    name: In Ufficio
    icon: mdi:worker

  tutteleluci:
    name: Tutte le luci
    icon: mdi:lightbulb

  buonanotte:
    name: Buonanotte
    
  autofranchino:
    name: Programmazione
    icon: mdi:calendar-clock
    initial: on

  timertvcamera:
    name: Timer TV Camera
    icon: mdi:timer

  mutoampli:
    name: Muto Ampli

  timerclima:
    name: Timer Clima
    icon: mdi:timer

  test:
    name: Test